Fatal error: Uncaught exception 'HH\InvariantException' with message 'Callback already registered: a' in :
Stack trace:
#0 (): HH\invariant_violation('Callback already registered: %s', 'a')
#1 (): HH\invariant(false, 'Callback already registered: %s', 'a')
#2 %s/test/slow/lang/invariant_cb_two.php(5): HH\invariant_callback_register('a')
#3 {main}