Caught
Caught
__ctor 1
__ctor 2
__ctor 3
__ctor 4
__ctor 5
__ctor 6
__ctor 7
__ctor 8
__ctor 9
__ctor 10
__ctor 11
__ctor 12
__ctor 13
__ctor 14
__ctor 15
signal throwing

Warning: signal handler 'signal_thrower' threw exception 'Exception' with message 'Sig exception' in %s/hphp/test/quick/profile/setprofile_throw.php:19
Stack trace:
#0 (): signal_thrower()
#1 %s/hphp/test/quick/profile/setprofile_throw.php(49): posix_kill()
#2 %s/hphp/test/quick/profile/setprofile_throw.php(93): func_entry()
#3 %s/hphp/test/quick/profile/setprofile_throw.php(97): main()
#4 {main} in %s/hphp/test/quick/profile/setprofile_throw.php on line 49
__dtor 15
__dtor 14
__dtor 13
__dtor 12
__dtor 11
__dtor 10
__dtor 9
__dtor 8
__dtor 7
__dtor 6
__dtor 5
__dtor 4
__dtor 3
__dtor 2
__dtor 1
__ctor 1
__ctor 2
__ctor 3
__ctor 4
__ctor 5
__ctor 6
__ctor 7
__ctor 8
__ctor 9
__ctor 10
__ctor 11
__ctor 12
__ctor 13
__ctor 14
__ctor 15
signal throwing

Warning: signal handler 'signal_thrower' threw exception 'Exception' with message 'Sig exception' in %s/hphp/test/quick/profile/setprofile_throw.php:19
Stack trace:
#0 (): signal_thrower()
#1 %s/hphp/test/quick/profile/setprofile_throw.php(75): posix_kill()
#2 %s/hphp/test/quick/profile/setprofile_throw.php(94): func_backward()
#3 %s/hphp/test/quick/profile/setprofile_throw.php(97): main()
#4 {main} in %s/hphp/test/quick/profile/setprofile_throw.php on line 75
__dtor 15
__dtor 14
__dtor 13
__dtor 12
__dtor 11
__dtor 10
__dtor 9
__dtor 8
__dtor 7
__dtor 6
__dtor 5
__dtor 4
__dtor 3
__dtor 2
__dtor 1
