====================== positive tests ========================
Exception: 'func1' called dynamically but is not __DynamicallyCallable

Warning: Decoding instance method func2$0$inout without $this! in %s on line %d
Exception: 'A::func2' called dynamically but is not __DynamicallyCallable
Exception: 'A::func3' called dynamically but is not __DynamicallyCallable

Warning: Decoding instance method func2$0$inout without $this! in %s on line %d
Exception: 'A::func2' called dynamically but is not __DynamicallyCallable
Exception: 'A::func3' called dynamically but is not __DynamicallyCallable
Exception: 'A::func2' called dynamically but is not __DynamicallyCallable
Exception: 'A::func3' called dynamically but is not __DynamicallyCallable
Exception: 'A::func3' called dynamically but is not __DynamicallyCallable
Exception: 'A::func3' called dynamically but is not __DynamicallyCallable
Exception: 'A::func2' called dynamically but is not __DynamicallyCallable
====================== negative tests ========================
