array(1) {
  [0]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/test/slow/ext_standard_errorfunc/debug_backtrace.php"
    ["line"]=>
    int(12)
    ["function"]=>
    string(3) "foo"
    ["args"]=>
    array(7) {
      [0]=>
      int(10)
      [1]=>
      string(1) "a"
      [2]=>
      object(stdClass)#1 (0) {
      }
      [3]=>
      object(A)#2 (0) {
      }
      [4]=>
      array(1) {
        [0]=>
        int(20)
      }
      [5]=>
      int(30)
      [6]=>
      NULL
    }
  }
}

Fatal error: Uncaught exception 'Exception' with message '' in %s/test/slow/ext_standard_errorfunc/debug_backtrace.php:5
Stack trace:
#0 %s/test/slow/ext_standard_errorfunc/debug_backtrace.php(12): foo(10, 'a', Object(stdClass), Object(A), Array, 30, NULL)
#1 {main}
